import { ThemeProvider } from '@/components/ThemeProvider';
import '@/styles/globals.css';
import {Toaster} from "@/components/ui/toaster"
// import Header from '@/components/Header'

export const metadata = {
  title: 'Task_assigner',
  description: 'Generated by Max',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Header/> */}
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
          <main>{children}</main>
          <Toaster/>
        </ThemeProvider>
      </body>
    </html>
  )
}
