import { ThemeProvider } from '@/components/ThemeProvider';
import '@/styles/globals.css';

export const metadata = {
  title: 'Task_assigner',
  description: 'Generated by Max',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
