import '@/styles/globals.css'; 

export const metadata = {
  title: 'Task_assigner',
  description: 'Generated by Max',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
